# Generated by Django 5.2.3 on 2025-10-20 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('draft', 'In Process'), ('done', 'Delivered')], default='draft', max_length=100),
        ),
    ]
