# Generated by Django 5.2.3 on 2025-09-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blogcategory_blog_remove_comment_blog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Blog Category'),
        ),
    ]
